"""adicionados 2 campos na tabela prescricao

Revision ID: 245cc71f19ae
Revises: 81b353a0cfc8
Create Date: 2025-09-21 20:27:35.834216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245cc71f19ae'
down_revision: Union[str, Sequence[str], None] = '81b353a0cfc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
