"""initial

Revision ID: c1245fed5498
Revises: 
Create Date: 2025-09-17 09:56:53.653856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1245fed5498'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idosos_cpf'), table_name='idosos')
    op.drop_index(op.f('ix_idosos_id'), table_name='idosos')
    op.drop_index(op.f('ix_idosos_nome_completo'), table_name='idosos')
    op.drop_table('idosos')
    op.drop_index(op.f('ix_responsaveis_cpf'), table_name='responsaveis')
    op.drop_index(op.f('ix_responsaveis_id'), table_name='responsaveis')
    op.drop_index(op.f('ix_responsaveis_nome_completo'), table_name='responsaveis')
    op.drop_table('responsaveis')
    op.drop_index(op.f('ix_prescricoes_id'), table_name='prescricoes')
    op.drop_table('prescricoes')
    op.drop_index(op.f('ix_administracao_log_id'), table_name='administracao_log')
    op.drop_table('administracao_log')
    op.drop_index(op.f('ix_medicamentos_id'), table_name='medicamentos')
    op.drop_index(op.f('ix_medicamentos_nome'), table_name='medicamentos')
    op.drop_table('medicamentos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicamentos',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('medicamentos_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unidade_medida', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='medicamentos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_medicamentos_nome'), 'medicamentos', ['nome'], unique=False)
    op.create_index(op.f('ix_medicamentos_id'), 'medicamentos', ['id'], unique=False)
    op.create_table('administracao_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_hora_administracao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id_prescricao', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_prescricao'], ['prescricoes.id'], name=op.f('administracao_log_id_prescricao_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('administracao_log_pkey'))
    )
    op.create_index(op.f('ix_administracao_log_id'), 'administracao_log', ['id'], unique=False)
    op.create_table('prescricoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dosagem', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('horario_prescrito', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('id_idoso', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_medicamento', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_idoso'], ['idosos.id'], name=op.f('prescricoes_id_idoso_fkey')),
    sa.ForeignKeyConstraint(['id_medicamento'], ['medicamentos.id'], name=op.f('prescricoes_id_medicamento_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prescricoes_pkey'))
    )
    op.create_index(op.f('ix_prescricoes_id'), 'prescricoes', ['id'], unique=False)
    op.create_table('responsaveis',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('responsaveis_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome_completo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='responsaveis_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_responsaveis_nome_completo'), 'responsaveis', ['nome_completo'], unique=False)
    op.create_index(op.f('ix_responsaveis_id'), 'responsaveis', ['id'], unique=False)
    op.create_index(op.f('ix_responsaveis_cpf'), 'responsaveis', ['cpf'], unique=True)
    op.create_table('idosos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_completo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cpf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data_nascimento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('quarto', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id_responsavel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_responsavel'], ['responsaveis.id'], name=op.f('idosos_id_responsavel_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('idosos_pkey'))
    )
    op.create_index(op.f('ix_idosos_nome_completo'), 'idosos', ['nome_completo'], unique=False)
    op.create_index(op.f('ix_idosos_id'), 'idosos', ['id'], unique=False)
    op.create_index(op.f('ix_idosos_cpf'), 'idosos', ['cpf'], unique=True)
    # ### end Alembic commands ###
